### ISSUE TITLE
Edit Question Page - Max Time Error

### ISSUE THREAD

**Issue by priyushasunkara** [GcvKishore/TMS#34]
Couldn't store the max time
![Bug1](https://user-images.githubusercontent.com/89763223/163199503-248a4a7d-d25f-487d-95e5-22a64ee9ace6.png)

**Comment by Vedvund** [comment]
Works fine I guess
![image](https://user-images.githubusercontent.com/86515503/163311634-8144a982-a8c5-44e8-8e93-4439b3756a2c.png)

**Comment by Vedvund** [comment]
The issue has not been resolved. Need to look into it deeply...

While adding question the Max Time gets saved but while editing exam it doesn't show the saved time and can't edit it
